/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppModesRouteImport } from './routes/_authenticated/_app/modes'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/_app/messages'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated/_app/feed'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/_app/discover'
import { Route as AuthenticatedAppMessagesIdRouteImport } from './routes/_authenticated/_app/messages.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModesRoute = AuthenticatedAppModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesIdRoute =
  AuthenticatedAppMessagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/feed': typeof AuthenticatedAppFeedRoute
  '/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/modes': typeof AuthenticatedAppModesRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/messages/$id': typeof AuthenticatedAppMessagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedAppDiscoverRoute
  '/feed': typeof AuthenticatedAppFeedRoute
  '/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/modes': typeof AuthenticatedAppModesRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/messages/$id': typeof AuthenticatedAppMessagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/_app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/_app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/_app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/_authenticated/_app/modes': typeof AuthenticatedAppModesRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/_app/messages/$id': typeof AuthenticatedAppMessagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/messages'
    | '/modes'
    | '/profile'
    | '/messages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/messages'
    | '/modes'
    | '/profile'
    | '/messages/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/dashboard'
    | '/_authenticated/_app/discover'
    | '/_authenticated/_app/feed'
    | '/_authenticated/_app/messages'
    | '/_authenticated/_app/modes'
    | '/_authenticated/_app/profile'
    | '/_authenticated/_app/messages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/modes': {
      id: '/_authenticated/_app/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof AuthenticatedAppModesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages': {
      id: '/_authenticated/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/feed': {
      id: '/_authenticated/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/discover': {
      id: '/_authenticated/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/messages/$id': {
      id: '/_authenticated/_app/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedAppMessagesIdRouteImport
      parentRoute: typeof AuthenticatedAppMessagesRoute
    }
  }
}

interface AuthenticatedAppMessagesRouteChildren {
  AuthenticatedAppMessagesIdRoute: typeof AuthenticatedAppMessagesIdRoute
}

const AuthenticatedAppMessagesRouteChildren: AuthenticatedAppMessagesRouteChildren =
  {
    AuthenticatedAppMessagesIdRoute: AuthenticatedAppMessagesIdRoute,
  }

const AuthenticatedAppMessagesRouteWithChildren =
  AuthenticatedAppMessagesRoute._addFileChildren(
    AuthenticatedAppMessagesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRouteWithChildren
  AuthenticatedAppModesRoute: typeof AuthenticatedAppModesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRouteWithChildren,
  AuthenticatedAppModesRoute: AuthenticatedAppModesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
